#Schedular
queue: normal
project: rp23
ncpus: 24
walltime: 2:00:00
jobname: CABLE-as-ACCESS
storage:
  gdata:
    - rp23

mpi:
  module: intel-mpi/2021.13.1

#Model
model: staged_cable
shortpath: /scratch/rp23
input:
  - /g/data/rp23/data/no_provenance/parameter
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/CABLE-as-ACCESS/MetForcing
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/CABLE-as-ACCESS/landmask
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/CABLE-as-ACCESS/gridinfo
exe: /home/564/lw5085/CABLE-main/bin/cable-mpi

restart_freq: 1
